# Generated by Django 3.0.3 on 2020-02-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decrypt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textfie', models.CharField(max_length=3000)),
            ],
        ),
    ]
